# Generated by Django 4.0.5 on 2022-06-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('resnum', models.CharField(help_text='residues that domain contains (e.g.[110-420])', max_length=20)),
                ('domainfile', models.FileField(null=True, upload_to='sitedb')),
            ],
        ),
        migrations.CreateModel(
            name='LigandInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ligname', models.CharField(max_length=3)),
                ('ligrank', models.IntegerField(default=1)),
                ('ligcoord', models.CharField(max_length=50)),
                ('mol2file', models.FileField(blank=True, null=True, upload_to='sitedb')),
            ],
            options={
                'ordering': ['ligrank'],
            },
        ),
        migrations.CreateModel(
            name='TemplateInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('templ_chain_lignum', models.CharField(help_text='e.g. 4KDH_A_100', max_length=50)),
                ('tmscore', models.FloatField()),
            ],
            options={
                'ordering': ['tmscore'],
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot', models.CharField(max_length=20)),
                ('protname', models.CharField(help_text='protein name given by uniprot', max_length=100, null=True)),
                ('proteintype', models.CharField(choices=[('PR', 'Protease'), ('GP', 'GPCR'), ('NHR', 'Nuclear Hormone Receptor'), ('KI', 'Kinase'), ('IC', 'Ion Channel'), ('UN', 'Unspecified')], max_length=3)),
                ('domains', models.ManyToManyField(blank=True, to='database.domain')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=1)),
                ('method', models.CharField(choices=[('sequence', 'sequence search'), ('structure', 'structure search')], default='sequence', max_length=10)),
                ('coordinate', models.CharField(help_text='Enter coordinate (e.g. (1.2983, 2.0900, -5.3980))', max_length=100)),
                ('uniquename', models.CharField(blank=True, max_length=100)),
                ('ligands', models.ManyToManyField(blank=True, to='database.ligandinstance')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.AddField(
            model_name='ligandinstance',
            name='templates',
            field=models.ManyToManyField(blank=True, to='database.templateinstance'),
        ),
        migrations.AddField(
            model_name='domain',
            name='sites',
            field=models.ManyToManyField(blank=True, to='database.site'),
        ),
    ]
