# Generated by Django 4.0.5 on 2022-06-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='seqcsvfile',
            field=models.FileField(null=True, upload_to='sitedb'),
        ),
        migrations.AddField(
            model_name='domain',
            name='strcsvfile',
            field=models.FileField(null=True, upload_to='sitedb'),
        ),
    ]
