# Generated by Django 4.0.5 on 2022-06-28 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_domain_seqcsvfile_domain_strcsvfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ['name']},
        ),
    ]
