# Generated by Django 4.0.5 on 2022-06-28 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_templateinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='target',
            options={'ordering': ['uniprot']},
        ),
    ]
