# Generated by Django 4.0.5 on 2022-06-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_target_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ['resnum']},
        ),
        migrations.AddField(
            model_name='domain',
            name='firstres',
            field=models.IntegerField(default=1),
        ),
    ]
