# Generated by Django 4.0.5 on 2022-06-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_alter_domain_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligandinstance',
            name='dockedfile',
            field=models.FileField(null=True, upload_to='sitedb'),
        ),
    ]
