# Generated by Django 4.0.5 on 2022-07-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_ligandinstance_dockedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligandinstance',
            name='liguniquename',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
