# Generated by Django 4.0.5 on 2022-07-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_ligandinstance_liguniquename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligandinstance',
            name='dockedfile',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='ligandinstance',
            name='mol2file',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
