# Generated by Django 4.0.5 on 2022-07-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_alter_ligandinstance_dockedfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligandinstance',
            name='dockedfile',
            field=models.FileField(null=True, upload_to='sitedb'),
        ),
        migrations.AlterField(
            model_name='ligandinstance',
            name='mol2file',
            field=models.FileField(blank=True, null=True, upload_to='sitedb'),
        ),
    ]
