# Generated by Django 4.0.5 on 2022-07-06 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_alter_ligandinstance_dockedfile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='target',
            options={'ordering': ['protname']},
        ),
    ]
