# Generated by Django 4.0.5 on 2022-08-23 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_alter_target_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='target',
            options={'ordering': ['uniprot']},
        ),
    ]
